import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const hum521b = localFont({
  src: "./fonts/HUM521N.ttf",
  variable: "--font-hum521b",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kun Humanity System+",
  description: "Generated by Kun Humanity System",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hum521b.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
